/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import Controller.*;
import Model.*;
import Model.Interfaces.Position;

/**
 *
 * @author danie_000
 */
public class AbilitieTreesGUI extends javax.swing.JFrame {

    MasterTree masterTree1 = new MasterTree(new Allen(), new Eddy(), new Pearl());

    boolean Allen;
    boolean Eddy;
    boolean Pearl;

    /**
     * Creates new form AbilitieTreesGUI
     */
    public AbilitieTreesGUI() {
        initComponents();
        Allen = false;
        Eddy = false;
        Pearl = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Pearl.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(300, 430, 120, 100);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Allen.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 430, 110, 100);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Eddy.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4);
        jLabel4.setBounds(140, 430, 150, 100);

        jButton1.setText("Apply Master");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(430, 470, 100, 23);

        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6);
        jLabel6.setBounds(60, 90, 40, 30);
        jPanel1.add(jLabel7);
        jLabel7.setBounds(60, 190, 40, 30);
        jPanel1.add(jLabel8);
        jLabel8.setBounds(60, 250, 40, 40);
        jPanel1.add(jLabel9);
        jLabel9.setBounds(60, 320, 40, 30);

        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10);
        jLabel10.setBounds(60, 390, 40, 20);
        jPanel1.add(jLabel11);
        jLabel11.setBounds(160, 90, 30, 30);
        jPanel1.add(jLabel12);
        jLabel12.setBounds(150, 190, 50, 30);
        jPanel1.add(jLabel13);
        jLabel13.setBounds(150, 260, 50, 20);
        jPanel1.add(jLabel14);
        jLabel14.setBounds(150, 320, 50, 30);
        jPanel1.add(jLabel15);
        jLabel15.setBounds(150, 390, 50, 20);
        jPanel1.add(jLabel16);
        jLabel16.setBounds(250, 90, 40, 30);
        jPanel1.add(jLabel17);
        jLabel17.setBounds(250, 190, 40, 30);
        jPanel1.add(jLabel18);
        jLabel18.setBounds(250, 260, 40, 20);
        jPanel1.add(jLabel19);
        jLabel19.setBounds(250, 320, 40, 30);
        jPanel1.add(jLabel20);
        jLabel20.setBounds(250, 380, 40, 30);
        jPanel1.add(jLabel21);
        jLabel21.setBounds(380, 100, 40, 30);
        jPanel1.add(jLabel22);
        jLabel22.setBounds(310, 130, 50, 30);
        jPanel1.add(jLabel23);
        jLabel23.setBounds(310, 190, 50, 30);
        jPanel1.add(jLabel24);
        jLabel24.setBounds(310, 260, 50, 20);
        jPanel1.add(jLabel25);
        jLabel25.setBounds(320, 320, 40, 20);
        jPanel1.add(jLabel26);
        jLabel26.setBounds(310, 380, 50, 30);
        jPanel1.add(jLabel27);
        jLabel27.setBounds(440, 130, 50, 30);
        jPanel1.add(jLabel28);
        jLabel28.setBounds(380, 190, 40, 30);
        jPanel1.add(jLabel29);
        jLabel29.setBounds(440, 190, 40, 30);
        jPanel1.add(jLabel30);
        jLabel30.setBounds(450, 260, 30, 20);
        jPanel1.add(jLabel31);
        jLabel31.setBounds(450, 320, 30, 20);
        jPanel1.add(jLabel32);
        jLabel32.setBounds(440, 380, 40, 30);
        jPanel1.add(jLabel33);
        jLabel33.setBounds(510, 190, 40, 30);
        jPanel1.add(jLabel34);
        jLabel34.setBounds(510, 250, 40, 40);
        jPanel1.add(jLabel35);
        jLabel35.setBounds(500, 310, 50, 40);
        jPanel1.add(jLabel36);
        jLabel36.setBounds(510, 350, 40, 60);
        jPanel1.add(jLabel37);
        jLabel37.setBounds(370, 250, 60, 30);
        jPanel1.add(jLabel38);
        jLabel38.setBounds(380, 320, 40, 30);
        jPanel1.add(jLabel39);
        jLabel39.setBounds(370, 390, 50, 30);

        jLabel40.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel40MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel40);
        jLabel40.setBounds(250, 0, 40, 60);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/AllenTree.PNG"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 0, 550, 420);

        jButton2.setText("jButton2");
        jPanel1.add(jButton2);
        jButton2.setBounds(460, 500, 73, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel40MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel40MouseClicked
        // TODO add your handling code here:

        jButton1.addMouseListener(new MouseAdapter() {
            
            
            
            
            public void mousePressed(MouseEvent e) {
                
                if (Allen) {
                    Position pos = masterTree1.applyMaster(masterTree1.allen,
                            masterTree1.getMasterTreeAllen(), 
                            masterTree1.getAllenPos2());
                    
                    masterTree1.setAllenPos2(pos);
                    System.out.println(masterTree1.allen.getHpLimit()+" "+masterTree1.allen.getMpLimit()+" "+masterTree1.allen.getArmor()+" "
                +masterTree1.allen.getAtk()+" "+masterTree1.allen.getSkill1().getMagic()+" "+masterTree1.allen.getSkill2().getMagic()+" "+masterTree1.allen.getSkill3().getMagic());
                    
                    
                } else if (Eddy) {
                    Position pos = masterTree1.applyMaster(masterTree1.eddy,
                            masterTree1.getMasterTreeEddy(), 
                            masterTree1.getEddyPos2());
                    
                    masterTree1.setAllenPos2(pos);
                } else if (Pearl) {
                    Position pos = masterTree1.applyMaster(masterTree1.pearl,
                            masterTree1.getMasterTreePearl(), 
                            masterTree1.getPearlPos2());
                    masterTree1.setPearlPos2(pos);
                }

            }

        }
        );

    }//GEN-LAST:event_jLabel40MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        Allen = true;
        Eddy = false;
        Pearl = false;
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        Allen = false;
        Eddy = true;
        Pearl = false;
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        Allen = false;
        Eddy = false;
        Pearl = true;
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AbilitieTreesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AbilitieTreesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AbilitieTreesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AbilitieTreesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AbilitieTreesGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
